# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ABetterPath.ui'
#
# Created: Tue Jan 10 23:11:46 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ABetterPathOptionsPage(object):
    def setupUi(self, ABetterPathOptionsPage):
        ABetterPathOptionsPage.setObjectName(_fromUtf8("ABetterPathOptionsPage"))
        ABetterPathOptionsPage.resize(410, 490)
        ABetterPathOptionsPage.setWindowTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget = QtGui.QTabWidget(ABetterPathOptionsPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 410, 490))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.alphaGroupBox = QtGui.QGroupBox(self.tab)
        self.alphaGroupBox.setGeometry(QtCore.QRect(0, 0, 191, 71))
        self.alphaGroupBox.setTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaGroupBox.setObjectName(_fromUtf8("alphaGroupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.alphaGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 171, 51))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.alphaLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.alphaLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.alphaLayout.setMargin(0)
        self.alphaLayout.setObjectName(_fromUtf8("alphaLayout"))
        self.artist_alphaLabel = QtGui.QLabel(self.formLayoutWidget)
        self.artist_alphaLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Alpha Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.artist_alphaLabel.setObjectName(_fromUtf8("artist_alphaLabel"))
        self.alphaLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.artist_alphaLabel)
        self.artist_alpha_numberLabel = QtGui.QLabel(self.formLayoutWidget)
        self.artist_alpha_numberLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Number Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.artist_alpha_numberLabel.setObjectName(_fromUtf8("artist_alpha_numberLabel"))
        self.alphaLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.artist_alpha_numberLabel)
        self.artist_alpha_number = QtGui.QLineEdit(self.formLayoutWidget)
        self.artist_alpha_number.setMaxLength(1)
        self.artist_alpha_number.setPlaceholderText(_fromUtf8(""))
        self.artist_alpha_number.setObjectName(_fromUtf8("artist_alpha_number"))
        self.alphaLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.artist_alpha_number)
        self.artist_alpha = QtGui.QCheckBox(self.formLayoutWidget)
        self.artist_alpha.setObjectName(_fromUtf8("artist_alpha"))
        self.alphaLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.artist_alpha)
        self.ArtistGroupBox = QtGui.QGroupBox(self.tab)
        self.ArtistGroupBox.setGeometry(QtCore.QRect(0, 80, 401, 111))
        self.ArtistGroupBox.setTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.ArtistGroupBox.setObjectName(_fromUtf8("ArtistGroupBox"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.ArtistGroupBox)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 251, 80))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.swapArtistNamesLabel = QtGui.QLabel(self.formLayoutWidget_5)
        self.swapArtistNamesLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Swap Names", None, QtGui.QApplication.UnicodeUTF8))
        self.swapArtistNamesLabel.setObjectName(_fromUtf8("swapArtistNamesLabel"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.swapArtistNamesLabel)
        self.artist_sort_name = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.artist_sort_name.setObjectName(_fromUtf8("artist_sort_name"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.artist_sort_name)
        self.prefixListLabel = QtGui.QLabel(self.formLayoutWidget_5)
        self.prefixListLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Prefix List", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixListLabel.setObjectName(_fromUtf8("prefixListLabel"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.prefixListLabel)
        self.artist_sort_prefix_list = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.artist_sort_prefix_list.setObjectName(_fromUtf8("artist_sort_prefix_list"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.artist_sort_prefix_list)
        self.swapArtistPrefixesLabel = QtGui.QLabel(self.formLayoutWidget_5)
        self.swapArtistPrefixesLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Swap Prefixes", None, QtGui.QApplication.UnicodeUTF8))
        self.swapArtistPrefixesLabel.setObjectName(_fromUtf8("swapArtistPrefixesLabel"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.swapArtistPrefixesLabel)
        self.artist_sort_prefix = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.artist_sort_prefix.setObjectName(_fromUtf8("artist_sort_prefix"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.artist_sort_prefix)
        self.VariousArtistsgroupBox = QtGui.QGroupBox(self.tab)
        self.VariousArtistsgroupBox.setGeometry(QtCore.QRect(200, 0, 201, 71))
        self.VariousArtistsgroupBox.setTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Various Artists", None, QtGui.QApplication.UnicodeUTF8))
        self.VariousArtistsgroupBox.setObjectName(_fromUtf8("VariousArtistsgroupBox"))
        self.formLayoutWidget_6 = QtGui.QWidget(self.VariousArtistsgroupBox)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.formLayoutWidget_6.setObjectName(_fromUtf8("formLayoutWidget_6"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.folderNameLabel = QtGui.QLabel(self.formLayoutWidget_6)
        self.folderNameLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Folder Name", None, QtGui.QApplication.UnicodeUTF8))
        self.folderNameLabel.setObjectName(_fromUtf8("folderNameLabel"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.folderNameLabel)
        self.artist_various = QtGui.QLineEdit(self.formLayoutWidget_6)
        self.artist_various.setObjectName(_fromUtf8("artist_various"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.artist_various)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.optionstab = QtGui.QWidget()
        self.optionstab.setObjectName(_fromUtf8("optionstab"))
        self.releaseGroupBox = QtGui.QGroupBox(self.optionstab)
        self.releaseGroupBox.setGeometry(QtCore.QRect(0, 80, 391, 271))
        self.releaseGroupBox.setTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Release", None, QtGui.QApplication.UnicodeUTF8))
        self.releaseGroupBox.setObjectName(_fromUtf8("releaseGroupBox"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.releaseGroupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 191, 80))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.catalogNumberLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.catalogNumberLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Catalog Number", None, QtGui.QApplication.UnicodeUTF8))
        self.catalogNumberLabel.setObjectName(_fromUtf8("catalogNumberLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.catalogNumberLabel)
        self.catalogNumberCheckBox = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.catalogNumberCheckBox.setObjectName(_fromUtf8("catalogNumberCheckBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.catalogNumberCheckBox)
        self.prefixLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.prefixLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLabel.setObjectName(_fromUtf8("prefixLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.prefixLabel)
        self.prefixLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.prefixLineEdit.setObjectName(_fromUtf8("prefixLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.prefixLineEdit)
        self.suffixLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.suffixLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Suffix", None, QtGui.QApplication.UnicodeUTF8))
        self.suffixLabel.setObjectName(_fromUtf8("suffixLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.suffixLabel)
        self.suffixLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.suffixLineEdit.setObjectName(_fromUtf8("suffixLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.suffixLineEdit)
        self.formLayoutWidget_3 = QtGui.QWidget(self.releaseGroupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 191, 151))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.dateLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.dateLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dateLabel.setObjectName(_fromUtf8("dateLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.dateLabel)
        self.dateCheckBox = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.dateCheckBox.setObjectName(_fromUtf8("dateCheckBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateCheckBox)
        self.prefixLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        self.prefixLabel_2.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLabel_2.setObjectName(_fromUtf8("prefixLabel_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.prefixLabel_2)
        self.prefixLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.prefixLineEdit_2.setObjectName(_fromUtf8("prefixLineEdit_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.prefixLineEdit_2)
        self.suffixLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        self.suffixLabel_2.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Suffix", None, QtGui.QApplication.UnicodeUTF8))
        self.suffixLabel_2.setObjectName(_fromUtf8("suffixLabel_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.suffixLabel_2)
        self.suffixLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.suffixLineEdit_2.setText(_fromUtf8(""))
        self.suffixLineEdit_2.setObjectName(_fromUtf8("suffixLineEdit_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.suffixLineEdit_2)
        self.granularityLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.granularityLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Granularity", None, QtGui.QApplication.UnicodeUTF8))
        self.granularityLabel.setObjectName(_fromUtf8("granularityLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.granularityLabel)
        self.granularityComboBox = QtGui.QComboBox(self.formLayoutWidget_3)
        self.granularityComboBox.setObjectName(_fromUtf8("granularityComboBox"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.granularityComboBox)
        self.separatorLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.separatorLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.separatorLabel.setObjectName(_fromUtf8("separatorLabel"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.separatorLabel)
        self.separatorLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.separatorLineEdit.setObjectName(_fromUtf8("separatorLineEdit"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.separatorLineEdit)
        self.padDateLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.padDateLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Pad Date", None, QtGui.QApplication.UnicodeUTF8))
        self.padDateLabel.setObjectName(_fromUtf8("padDateLabel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.padDateLabel)
        self.padDateLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.padDateLineEdit.setObjectName(_fromUtf8("padDateLineEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.padDateLineEdit)
        self.formLayoutWidget_4 = QtGui.QWidget(self.releaseGroupBox)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(220, 20, 160, 101))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.discSubfolderLabel = QtGui.QLabel(self.formLayoutWidget_4)
        self.discSubfolderLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Disc Subfolder", None, QtGui.QApplication.UnicodeUTF8))
        self.discSubfolderLabel.setObjectName(_fromUtf8("discSubfolderLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.discSubfolderLabel)
        self.discSubfolderComboBox = QtGui.QComboBox(self.formLayoutWidget_4)
        self.discSubfolderComboBox.setObjectName(_fromUtf8("discSubfolderComboBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.discSubfolderComboBox)
        self.prefixLabel_3 = QtGui.QLabel(self.formLayoutWidget_4)
        self.prefixLabel_3.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLabel_3.setObjectName(_fromUtf8("prefixLabel_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.prefixLabel_3)
        self.prefixLineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.prefixLineEdit_3.setObjectName(_fromUtf8("prefixLineEdit_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.prefixLineEdit_3)
        self.separatorLabel_2 = QtGui.QLabel(self.formLayoutWidget_4)
        self.separatorLabel_2.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.separatorLabel_2.setObjectName(_fromUtf8("separatorLabel_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.separatorLabel_2)
        self.separatorLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.separatorLineEdit_2.setObjectName(_fromUtf8("separatorLineEdit_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.separatorLineEdit_2)
        self.tabWidget.addTab(self.optionstab, _fromUtf8(""))
        self.liststab = QtGui.QWidget()
        self.liststab.setObjectName(_fromUtf8("liststab"))
        self.tabWidget.addTab(self.liststab, _fromUtf8(""))

        self.retranslateUi(ABetterPathOptionsPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ABetterPathOptionsPage)

    def retranslateUi(self, ABetterPathOptionsPage):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("ABetterPathOptionsPage", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionstab), QtGui.QApplication.translate("ABetterPathOptionsPage", "Album", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.liststab), QtGui.QApplication.translate("ABetterPathOptionsPage", "Lists", None, QtGui.QApplication.UnicodeUTF8))

