# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ABetterPath.ui'
#
# Created: Mon Jan 09 09:55:17 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ABetterPathOptionsPage(object):
    def setupUi(self, ABetterPathOptionsPage):
        ABetterPathOptionsPage.setObjectName(_fromUtf8("ABetterPathOptionsPage"))
        ABetterPathOptionsPage.resize(410, 490)
        ABetterPathOptionsPage.setWindowTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget = QtGui.QTabWidget(ABetterPathOptionsPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 410, 490))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.optionstab = QtGui.QWidget()
        self.optionstab.setObjectName(_fromUtf8("optionstab"))
        self.releaseGroupBox = QtGui.QGroupBox(self.optionstab)
        self.releaseGroupBox.setGeometry(QtCore.QRect(0, 80, 391, 271))
        self.releaseGroupBox.setTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Release", None, QtGui.QApplication.UnicodeUTF8))
        self.releaseGroupBox.setObjectName(_fromUtf8("releaseGroupBox"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.releaseGroupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 180, 191, 80))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.catalogNumberLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.catalogNumberLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Catalog Number", None, QtGui.QApplication.UnicodeUTF8))
        self.catalogNumberLabel.setObjectName(_fromUtf8("catalogNumberLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.catalogNumberLabel)
        self.catalogNumberCheckBox = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.catalogNumberCheckBox.setObjectName(_fromUtf8("catalogNumberCheckBox"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.catalogNumberCheckBox)
        self.prefixLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.prefixLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLabel.setObjectName(_fromUtf8("prefixLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.prefixLabel)
        self.prefixLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.prefixLineEdit.setObjectName(_fromUtf8("prefixLineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.prefixLineEdit)
        self.suffixLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.suffixLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Suffix", None, QtGui.QApplication.UnicodeUTF8))
        self.suffixLabel.setObjectName(_fromUtf8("suffixLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.suffixLabel)
        self.suffixLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.suffixLineEdit.setObjectName(_fromUtf8("suffixLineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.suffixLineEdit)
        self.formLayoutWidget_3 = QtGui.QWidget(self.releaseGroupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 191, 151))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.dateLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.dateLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.dateLabel.setObjectName(_fromUtf8("dateLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.dateLabel)
        self.dateCheckBox = QtGui.QCheckBox(self.formLayoutWidget_3)
        self.dateCheckBox.setObjectName(_fromUtf8("dateCheckBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateCheckBox)
        self.prefixLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        self.prefixLabel_2.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLabel_2.setObjectName(_fromUtf8("prefixLabel_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.prefixLabel_2)
        self.prefixLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.prefixLineEdit_2.setObjectName(_fromUtf8("prefixLineEdit_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.prefixLineEdit_2)
        self.suffixLabel_2 = QtGui.QLabel(self.formLayoutWidget_3)
        self.suffixLabel_2.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Suffix", None, QtGui.QApplication.UnicodeUTF8))
        self.suffixLabel_2.setObjectName(_fromUtf8("suffixLabel_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.suffixLabel_2)
        self.suffixLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.suffixLineEdit_2.setText(_fromUtf8(""))
        self.suffixLineEdit_2.setObjectName(_fromUtf8("suffixLineEdit_2"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.suffixLineEdit_2)
        self.granularityLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.granularityLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Granularity", None, QtGui.QApplication.UnicodeUTF8))
        self.granularityLabel.setObjectName(_fromUtf8("granularityLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.granularityLabel)
        self.granularityComboBox = QtGui.QComboBox(self.formLayoutWidget_3)
        self.granularityComboBox.setObjectName(_fromUtf8("granularityComboBox"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.granularityComboBox)
        self.separatorLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.separatorLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.separatorLabel.setObjectName(_fromUtf8("separatorLabel"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.separatorLabel)
        self.separatorLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.separatorLineEdit.setObjectName(_fromUtf8("separatorLineEdit"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.separatorLineEdit)
        self.padDateLabel = QtGui.QLabel(self.formLayoutWidget_3)
        self.padDateLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Pad Date", None, QtGui.QApplication.UnicodeUTF8))
        self.padDateLabel.setObjectName(_fromUtf8("padDateLabel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.padDateLabel)
        self.padDateLineEdit = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.padDateLineEdit.setObjectName(_fromUtf8("padDateLineEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.padDateLineEdit)
        self.formLayoutWidget_4 = QtGui.QWidget(self.releaseGroupBox)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(220, 20, 160, 101))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.discSubfolderLabel = QtGui.QLabel(self.formLayoutWidget_4)
        self.discSubfolderLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Disc Subfolder", None, QtGui.QApplication.UnicodeUTF8))
        self.discSubfolderLabel.setObjectName(_fromUtf8("discSubfolderLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.discSubfolderLabel)
        self.discSubfolderComboBox = QtGui.QComboBox(self.formLayoutWidget_4)
        self.discSubfolderComboBox.setObjectName(_fromUtf8("discSubfolderComboBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.discSubfolderComboBox)
        self.prefixLabel_3 = QtGui.QLabel(self.formLayoutWidget_4)
        self.prefixLabel_3.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixLabel_3.setObjectName(_fromUtf8("prefixLabel_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.prefixLabel_3)
        self.prefixLineEdit_3 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.prefixLineEdit_3.setObjectName(_fromUtf8("prefixLineEdit_3"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.prefixLineEdit_3)
        self.separatorLabel_2 = QtGui.QLabel(self.formLayoutWidget_4)
        self.separatorLabel_2.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Separator", None, QtGui.QApplication.UnicodeUTF8))
        self.separatorLabel_2.setObjectName(_fromUtf8("separatorLabel_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.separatorLabel_2)
        self.separatorLineEdit_2 = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.separatorLineEdit_2.setObjectName(_fromUtf8("separatorLineEdit_2"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.separatorLineEdit_2)
        self.ArtistGroupBox = QtGui.QGroupBox(self.optionstab)
        self.ArtistGroupBox.setGeometry(QtCore.QRect(0, 350, 391, 111))
        self.ArtistGroupBox.setTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Artist", None, QtGui.QApplication.UnicodeUTF8))
        self.ArtistGroupBox.setObjectName(_fromUtf8("ArtistGroupBox"))
        self.formLayoutWidget_5 = QtGui.QWidget(self.ArtistGroupBox)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 251, 80))
        self.formLayoutWidget_5.setObjectName(_fromUtf8("formLayoutWidget_5"))
        self.formLayout_5 = QtGui.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.swapArtistNamesLabel = QtGui.QLabel(self.formLayoutWidget_5)
        self.swapArtistNamesLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Swap Names", None, QtGui.QApplication.UnicodeUTF8))
        self.swapArtistNamesLabel.setObjectName(_fromUtf8("swapArtistNamesLabel"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.swapArtistNamesLabel)
        self.swapArtistNamesCheckBox = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.swapArtistNamesCheckBox.setObjectName(_fromUtf8("swapArtistNamesCheckBox"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.swapArtistNamesCheckBox)
        self.prefixListLabel = QtGui.QLabel(self.formLayoutWidget_5)
        self.prefixListLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Prefix List", None, QtGui.QApplication.UnicodeUTF8))
        self.prefixListLabel.setObjectName(_fromUtf8("prefixListLabel"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.prefixListLabel)
        self.prefixListLineEdit = QtGui.QLineEdit(self.formLayoutWidget_5)
        self.prefixListLineEdit.setObjectName(_fromUtf8("prefixListLineEdit"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.prefixListLineEdit)
        self.swapArtistPrefixesLabel = QtGui.QLabel(self.formLayoutWidget_5)
        self.swapArtistPrefixesLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Swap Prefixes", None, QtGui.QApplication.UnicodeUTF8))
        self.swapArtistPrefixesLabel.setObjectName(_fromUtf8("swapArtistPrefixesLabel"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.swapArtistPrefixesLabel)
        self.swapArtistPrefixesCheckBox = QtGui.QCheckBox(self.formLayoutWidget_5)
        self.swapArtistPrefixesCheckBox.setObjectName(_fromUtf8("swapArtistPrefixesCheckBox"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.swapArtistPrefixesCheckBox)
        self.alphaGroupBox = QtGui.QGroupBox(self.optionstab)
        self.alphaGroupBox.setGeometry(QtCore.QRect(0, 0, 391, 80))
        self.alphaGroupBox.setTitle(QtGui.QApplication.translate("ABetterPathOptionsPage", "Artist Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaGroupBox.setObjectName(_fromUtf8("alphaGroupBox"))
        self.formLayoutWidget = QtGui.QWidget(self.alphaGroupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 171, 51))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.alphaLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.alphaLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.alphaLayout.setMargin(0)
        self.alphaLayout.setObjectName(_fromUtf8("alphaLayout"))
        self.alphaLabel = QtGui.QLabel(self.formLayoutWidget)
        self.alphaLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Alpha Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaLabel.setObjectName(_fromUtf8("alphaLabel"))
        self.alphaLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.alphaLabel)
        self.alphaNumberLabel = QtGui.QLabel(self.formLayoutWidget)
        self.alphaNumberLabel.setText(QtGui.QApplication.translate("ABetterPathOptionsPage", "Number Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.alphaNumberLabel.setObjectName(_fromUtf8("alphaNumberLabel"))
        self.alphaLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.alphaNumberLabel)
        self.alphaNumberEdit = QtGui.QLineEdit(self.formLayoutWidget)
        self.alphaNumberEdit.setMaxLength(1)
        self.alphaNumberEdit.setPlaceholderText(_fromUtf8(""))
        self.alphaNumberEdit.setObjectName(_fromUtf8("alphaNumberEdit"))
        self.alphaLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.alphaNumberEdit)
        self.alphaCheckBox = QtGui.QCheckBox(self.formLayoutWidget)
        self.alphaCheckBox.setObjectName(_fromUtf8("alphaCheckBox"))
        self.alphaLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.alphaCheckBox)
        self.tabWidget.addTab(self.optionstab, _fromUtf8(""))
        self.liststab = QtGui.QWidget()
        self.liststab.setObjectName(_fromUtf8("liststab"))
        self.tabWidget.addTab(self.liststab, _fromUtf8(""))

        self.retranslateUi(ABetterPathOptionsPage)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ABetterPathOptionsPage)

    def retranslateUi(self, ABetterPathOptionsPage):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optionstab), QtGui.QApplication.translate("ABetterPathOptionsPage", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.liststab), QtGui.QApplication.translate("ABetterPathOptionsPage", "Lists", None, QtGui.QApplication.UnicodeUTF8))

